[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHONUNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"
